### PR TITLE
reduce requirements

### PR DESCRIPTION
**Pull request by k-nut**
I think the current requirements.txt contains way too many requirements (e.g things related to Flask).
I tried to start from an empty file and just added the ones that were required to get `./run.py` to
work. 

Maybe I'm missing something here?

### CODE REVIEW

**Comment by tursics** [comment]
ModuleNotFoundError: No module named 'w3lib'

This error will be fixed if you install scrapy with all dependencies (for python 3.7)
pip install git+https://github.com/scrapy/scrapy@master --upgrade

**Comment by tursics** [comment]
@k-nut I use a fresh installed Python 3.7.0

**Comment by k-nut** [comment]
So @tursics you get this error when you run `pip install git+https://github.com/scrapy/scrapy@master --upgrade` with Python3.7, right? Are you doing this on macOS or on Windows?

**Comment by tursics** [comment]
I'm using macOS with Python 3.7.0 and your changes fix my installation problems.

Thanks a lot

**Comment by cyroxx** [comment]
I strongly support this PR, the current list of requirements is way too long. Many of those packages are not even a dependency (docker, jupyter, twitter, just to name a few).

What is missing though, is scrapy itself, so you might want to add `scrapy==1.5.0` (or maybe a newer version) to `requirements.txt` back again?

**Comment by k-nut** [comment]
Scrapy now also work with Python 3.7. 

I updated the README and removed my comment about this.

**Pull request merged**
