### PR TITLE
Aktualisiere NRW Parser, fixes #34

### LINKED ISSUE #34: NRW: Scraper aktualisieren
Der Scraper für NRW liefert aktuell nur ein leeres Ergebnis (`[]`).

Die neue Einstiegsseite sollte vermutlich diese sein: https://www.schulministerium.nrw.de/BiPo/SchuleSuchen/online?action=829.4479020997484

@lislis, da du zuletzt im April neue Daten für NRW bereitgestellt hast (Datenschule/schulscraper-data@c4f14d314799a37e022cfd8f0f62a121acac73b7): Hast du vielleicht schon eine Version des Scrapers, der mit der geänderten Website umgehen kann?

### PR DESCRIPTION
**Pull request by cyroxx**
Erster Wurf einer Aktualisierung des Parsers. Wie in #34 beschrieben, holt er sich zumindest jetzt wieder die Grunddaten.

### CODE REVIEW

**Comment by k-nut** [comment]
Extract from the new `data/nrw.json`:

```
  {
    "Schulnummer": "600978",
    "Schulform": "0A",
    "Schulbezeichnung_1": "Schulamt",
    "Schulbezeichnung_2": "für den Kreis Unna",
    "Schulbezeichnung_3": "",
    "Kurzbezeichnung": "Unna, Schulamt Kreis Unna",
    "PLZ": "59425",
    "Ort": "Unna",
    "Strasse": "Parkstr. 40b",
    "Telefonvorwahl": "02303",
    "Telefon": "27-0",
    "Faxvorwahl": "02303",
    "Fax": "271996",
    "E-Mail": "600978@schule.nrw.de",
    "Homepage": "http://www.kreis-unna.de",
    "Rechtsform": "1",
    "Traegernummer": "0",
    "Gemeindeschluessel": "05978036",
    "Schulbetriebsschluessel": "1",
    "Schulbetriebsdatum": "01.08.1973",
    "EPSG": "EPSG:25832",
    "UTMRechtswert": "409229",
    "UTMHochwert": "5711194"
  }
```

Do we need to change any post processing scripts for this @knutator2 ?

**Comment by knutator2** [comment]
I think we only need to change the processing script in the repository for jedeschule-data, But nothing in this repo.

**Comment by cyroxx** [comment]
With 83f6bc2, the above example looks like this:

```
{
  "E-Mail": "600978@schule.nrw.de",
  "Schulbezeichnung_3": "",
  "Schulformschluessel": "0A",
  "Homepage": "http://www.kreis-unna.de",
  "Faxvorwahl": "02303",
  "Schulbetriebsschluessel": "1",
  "Fax": "271996",
  "PLZ": "59425",
  "Schulbezeichnung_2": "für den Kreis Unna",
  "Rechtsformschluessel": "1",
  "Telefonvorwahl": "02303",
  "Telefon": "27-0",
  "Schulnummer": "600978",
  "EPSG": "EPSG:25832",
  "Gemeindeschluessel": "05978036",
  "Schulbetriebsdatum": "01.08.1973",
  "Ort": "Unna",
  "UTMHochwert": "5711194",
  "Rechtsform": "in öffentlicher Trägerschaft",
  "Schulbezeichnung_1": "Schulamt",
  "Schulform": "Schulaufsicht",
  "Traeger": null,
  "Schuelerzahl": null,
  "UTMRechtswert": "409229",
  "Schulbetrieb": "Schule hat Schulbetrieb",
  "Kurzbezeichnung": "Unna, Schulamt Kreis Unna",
  "Traegernummer": "0",
  "Strasse": "Parkstr. 40b"
}
```
Rechtsform, Schulform, Schulbetrieb and Traeger are expanded (de-normalized) and Schuelerzahl was added.
In order to see the full impact of the changes, let's see an actual school (the above example is only a school authority [Schulamt]):

```
{
  "E-Mail": "100010@schule.nrw.de",
  "Schulbezeichnung_3": "im Aufbau d. CAPS Privatschu gGmbH",
  "Schulformschluessel": "20",
  "Homepage": "http://www.claudia-agrippina-privatschule.de",
  "Faxvorwahl": "0221",
  "Schulbetriebsschluessel": "1",
  "Fax": "37990671",
  "PLZ": "50933",
  "Schulbezeichnung_2": "schule als priv.Ersatzsch. d. Sek.I u.II",
  "Rechtsformschluessel": "2",
  "Telefonvorwahl": "0221",
  "Telefon": "37996433",
  "Schulnummer": "100010",
  "EPSG": "EPSG:25832",
  "Gemeindeschluessel": "05315000",
  "Schulbetriebsdatum": "01.08.2016",
  "Ort": "Köln",
  "UTMHochwert": "5645500",
  "Rechtsform": "in Trägerschaft eines Ersatzschulträgers (privat)",
  "Schulbezeichnung_1": "Aufbaugymnasium Claudia Agrippina Privat",
  "Schulform": "Gymnasium",
  "Traeger": {
    "Traegerbezeichnung_1": "CAPS Privatschul gGmbH",
    "Gemeindeschluessel": "05315000",
    "Traegerbezeichnung_2": "",
    "Faxvorwahl": "0221",
    "Fax": "37990671",
    "PLZ": "50933",
    "Traegerbezeichnung_3": "",
    "Ort": "Köln",
    "Telefonvorwahl": "0221",
    "Telefon": "37996433",
    "Kurzbezeichnung": "Köln, CAPS Privatschul gGmbH",
    "Traegernummer": "83150",
    "Strasse": "Stolberger Straße 112"
  },
  "Schuelerzahl": "98",
  "UTMRechtswert": "352258",
  "Schulbetrieb": "Schule hat Schulbetrieb",
  "Kurzbezeichnung": "Köln, Gym Claudia Agrippina Aufbaugym.",
  "Traegernummer": "83150",
  "Strasse": "Stolberger Str. 112"
}
```

**Comment by k-nut** [comment]
@cyroxx can we maybe also use this as a chance to move the NRW specific code out of `run.py`? I'd propose that we create a new folder `jedeschule/data_downloaders` (or something like that) so that we can see that we have a) spiders that parse HTML and b) "open data downloaders. In the new folder, we could then also have one file per state just like we do for the spiders. What do you think?

**Pull request merged**
