### PR TITLE
Test models

### PR DESCRIPTION
**Pull request by k-nut**

### CODE REVIEW

**Comment by k-nut** [comment]
Curiously the test fail with Python3.8 when pip installing here. @stefanw did you manage to run it with 3.8 locally?

**Comment by stefanw** [comment]
The test fail seems to be a failing install of libxml (missing headers?).

**Comment by k-nut** [comment]
Nice, that actually was what it was. Fixed here: 502b9451edbf2a2

**Comment by knutator2** [comment]
i think it would be nice to clear the database before the test, so we have a clean db and know its state. What do you think?

**Comment by k-nut** [comment]
@knutator2 as the `./test.sh` script creates a temporary database and removes it afterwards we know that the data will always be in the same state, don't we?

**Comment by knutator2** [comment]
ah ok, i didn't recognize, the tests depend on each other. I just thought every test should assume an empty database and sets up the database as needed for the test. Nevertheless, works for me right now

**Pull request merged**
