### PR TITLE
Feature bremen crawler

### PR DESCRIPTION
**Pull request by MartinGer**
fix data, extract address and phone/fax numbers correctly

### CODE REVIEW

**Comment by knutator2** [comment]
there still seems an issue with a couple of items: some just give somethin like {"name": null, "id": 1001} into the normalize pipe

out of curiosity why do you set the global id to 1000 instead of using the id in the data?

**Comment by MartinGer** [comment]
> there still seems an issue with a couple of items: some just give somethin like {"name": null, "id": 1001} into the normalize pipe
> 
> out of curiosity why do you set the global id to 1000 instead of using the id in the data?

I didn't change the crawler itself and just fixed that there wasn't any Id. That's why I just added a running one with four letters to make sure that all are uniform in size. Could be changed though.

**Comment by cyroxx** [comment]
Shouldn't we use those IDs?
Screenshot Schulwegweiser Bremen

**Comment by MartinGer** [comment]
The Id of the website will be used now

**Pull request merged**
